feat: Camunda Modeler 5 compatibility patch
camunda/camunda-modeler-process-io-specification-plugin pull request #22
Opened 2022-03-18 12:07 UTC by Skaiir

* migrated to latest properties panel
* cleaned up repo

Closes #17
Closes #20
Closes #21

2022-03-18 12:21 UTC, Skaiir commented
Somehow managed to merge this one manually without breaking everything.

2022-03-18 12:32 UTC, barmac commented
Let's update the compatibility table as well: https://github.com/camunda/camunda-modeler-process-io-specification-plugin/tree/migrate-to-latest-properties-panel#compatibility-notice

2022-03-18 12:51 UTC, barmac commented
> Merge branch 'master' into migrate-to-latest-properties-panel

How about if we just rebase and have no merge commits in the PR?

2022-03-18 14:58 UTC, barmac requested changes

2022-03-18 14:58 UTC, barmac commented on CHANGELOG.md
> +**\_Note:** Yet to be released changes appear here.\_
```suggestion
___Note:__ Yet to be released changes appear here._
```

Let's not change styles.

2022-03-18 17:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-modeler-process-io-specification-plugin?pullRequest=22) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-modeler-process-io-specification-plugin?pullRequest=22) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Skaiir<br/>:x: barmac<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-modeler-process-io-specification-plugin?pullRequest=22) it.</sub>

2022-03-21 06:59 UTC, closed without merging

2022-03-21 07:00 UTC, Skaiir commented
This is followed up in #22 since I can't squash a merge commit out of the git history.